version: '3'

services:

  flask-server:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./templates:/app/templates

  ibm:
    image: codait/max-inception-resnet-v2
    ports:
      - "5002:5000"
